### ISSUE TITLE
Graphite Target selection

### ISSUE THREAD

**Issue by luxflux** [fdietz/team_dashboard#3]
We have about 10400 metrics in graphite. So the target selection autocompletion is quite laggy :) I think memcache would be quite cool or we could start with saving them to the database at first. What do you think about it?

Also the longest paths have up to 83 signs, so the field is way to small to display the full path and even with the line break it is not so easy to use :)
What do you think about a tree view like the one the Graphite composer uses?

**Comment by fdietz** [comment]
Hi luxflux!

As a first step (quick win!) I suggest we simple fetch the metrics list once instead of everytime the user switches the source in the widget edit dialog. Then it will be fetched again only if you refresh your browser page. 

I'm not sure if caching the metrics list in memcache or mysql instead of fetching it from graphite will further improve the user experience. At the end you still have to do a HTTP request for the complete list. Is graphite really that much slower? If we go down that road I would suggest to store them in a way we can request metrics already filtered very fast suitable for an autosuggest/complete feature and implement a REST service with a query string param.

I wholeheartly agree that the current autosuggest textfield (using currently the jquery select2 plugin) usability does not scale very well :-) So, I really like starting the discussion now. I personally don't like the tree view to select Graphite metrics since I end up with quite a few mouse clicks until I've drilled down deep enough in the tree hierarchy. Even though I have to admit being able to browse through all the metrics is nice.

My goal for the metrics selection is a generic approach which fits all kinds of data sources. Graphite is only one of them, I'm currently working on Ganglia (still waiting for a fix here though). They have completely different properties (Ganglia uses cluster name, hostname and metric name) to identify their "metric name" (I called it actually datapoint targets in the source code).  So, using a tree view would be counterproductive to this goal and would mean we'd have to eventually implement different types of target selectors. I'd rather like in this early project state avoid it until we have a better understanding of the various data source plugin requirements. Additionally, there's a lot of boilerplate code involved here I want to reduce/cleanup first, before adding more features.

I was actually experimenting with different versions of this UI element and my idea was to start with a list of targets were you can add and remove entries. When adding an entry you have to press the "Add ..." button which opens a new modal dialog to select your target. This could be a much larger textfield with autosuggest or a list/tree view with a search/filter. Point is to move the actual source-specific configuration options (for datapoints the target selection) or maybe only the target selection out of the form. Another reason why I wanna go this way is to give immediate feedback on for example http_proxy sources with a JSON path selection, let the user play around with the results.

Quite a long answer already and I don't have neither quick answer or solution for you at this stage ;-) But, at least you know that I'm aware of these issues and also pondering on them for quite a while already.

Cheers,
-Frederik

**Comment by luxflux** [comment]
Hi Frederik

On 08/11/2012 08:23 PM, Frederik Dietz wrote:

> I'm not sure if caching the metrics list in memcache or mysql
> instead of fetching it from graphite will further improve the user
> experience. At the end you still have to do a HTTP request for the
> complete list. Is graphite really that much slower? If we go down
> that road I would suggest to store them in a way we can request
> metrics already filtered very fast suitable for an
> autosuggest/complete feature and implement a REST service with a
> query string param.

This sounds good! I played around a bit and found out, that its more
my browser and not graphite. Fetching the datapoints takes about one
second. But when I start typing it's laggy at first. But according to
the network-tab it does not request anymore data from the server... I
think fetching them once (as you suggested) in the background when you
did not already open the "Add Widget"-dialog would be fine. Maybe a
button to refresh it in the "Add Widget"-dialog? So you would not have
to reload the whole page again if there was a metric added...

> I wholeheartly agree that the current autosuggest textfield (using 
> currently the jquery select2 plugin) usability does not scale very
> well :-) So, I really like starting the discussion now. I
> personally don't like the tree view to select Graphite metrics
> since I end up with quite a few mouse clicks until I've drilled
> down deep enough in the tree hierarchy. Even though I have to admit
> being able to browse through all the metrics is nice.

I often forget which path lead me to the metric I need, so browsing
the whole thing is kind of a need for me :) But you can do such a
browsing also with autocompletion :P

> [...]
> 
> I was actually experimenting with different versions of this UI
> element and my idea was to start with a list of targets were you
> can add and remove entries. When adding an entry you have to press
> the "Add ..." button which opens a new modal dialog to select your
> target. This could be a much larger textfield with autosuggest or a
> list/tree view with a search/filter. Point is to move the actual
> source-specific configuration options (for datapoints the target
> selection) or maybe only the target selection out of the form.
> Another reason why I wanna go this way is to give immediate
> feedback on for example http_proxy sources with a JSON path
> selection, let the user play around with the results.

This sounds really cool! So you could even do something with tabs in
the "Add.."-Dialog where you could work with autocompletion or a tree
view. Also the live preview would be great!

If you need any help with all this, please tell me. I really like this
dashboard and would like to contribute! I normally code ruby, but
javascript is not a foreign language for me. Only the whole
Backbone.js stuff I never used before :)

regards
 raf

**Comment by fdietz** [comment]
Hi raf!

I thought about this some more and suggest to do this in 3 steps then:
1. do not re-fetch metrics if possible (think of a way to update them easily in the background, preferably without requiring user interaction)
2. improve usability of current metric/target UI element, by introducing a simpler autosuggest textfield and a list combination
3. add browsing dialog (with list/tree ui element)

Here's a wireframe of the UI elements: https://www.dropbox.com/s/ru2fp01euv5dss2/widget_edit_dialog.png

Kind regards,
-Frederik

**Comment by fdietz** [comment]
Hi raf!

I've commited a quick fix for 1) to not refetch metrics. You need to reload your browser to fetch metrics from scratch. Will improve on this later.

Additionally, there's now an initial (although quite rough) fix for 2) available. Following the design it uses a autosuggest textfield and a real list.

The actual browing 3) will take some more time though. 

Let me know if everything works for you!

Cheers,
-Frederik

**Comment by fdietz** [comment]
Hi again,

I've created separate issues for 1) and 2) since I want to have them in the next v0.3.0 release. I'm using milestones for the issues now.

The actual browsing 3) will be then in v0.4.0.

-Frederik

**Comment by fdietz** [comment]
Hi again,

I've pushed an initial version of metrics browser:
https://github.com/fdietz/team_dashboard/commit/f8c72bda329657bfed867d150a4c9462e7b672df

Note, that its simply a list which can be filtered via textfield. Maximum number of item shown is actually 200, so you have to use the filtering to make it work for you. This hopefully ensures that the list feels very snappy in comparison to trying to create dom nodes for all available metrics.

I've intentionally not implemented a tree view since it would have been much more complicated, even when using existing jquery plugins. 

So, please let me know if the browser works for you!

**Comment by luxflux** [comment]
Hi Frederik

On 08/19/2012 07:52 PM, Frederik Dietz wrote:

> Note, that its simply a list which can be filtered via textfield. 
> Maximum number of item shown is actually 200, so you have to use
> the filtering to make it work for you. This hopefully ensures that
> the list feels very snappy in comparison to trying to create dom
> nodes for all available metrics.
> 
> I've intentionally not implemented a tree view since it would have
> been much more complicated, even when using existing jquery
> plugins.
> 
> So, please let me know if the browser works for you!

Yay, good start! I like it. One small addition: Would be cool to be
able to double-click the entries to select them :)

What do you think about implementing Graphite-Functions? I've got some
gauge values from which I would like to have the derivative. So I need
to be able to select 'nonNegativeDerivative(path.to.gauge)' for example.
Maybe https://github.com/ripienaar/graphite-graph-dsl would be a nice
start to create the urls? See
https://github.com/ripienaar/graphite-graph-dsl/wiki/Using-in-Ruby to
see how to access the DSL from ruby.

Maybe this would be a nice replacement or extension of GraphiteURLBuilder?

Is there something similar for ganglia?

regards
 raf

**Comment by fdietz** [comment]
Thanks for the feedback. I've added double click handling, BTW ;-)

You can actually (in theory) use functions right away. Since the current version treats all targets as a string and will send them as is to graphite. So, enter in the textfield 'nonNegativeDerivative(path.to.gauge)' and it should work.

I've quickly looked into the graphite-graph-dsl and it nicely packages the url building. So, it might be interesting to investigate the possibility to replace our own custom code with this gem.

On the other hand besides adding functions (and events) there's not much else I need. How about you? Do you need some/all the "configuration properties" offered by graphite and used in the dashboard? It would be cool to come up with a list of the most important ones and focus on these next (with or without the gem).

Ideally we would have a nice dialog for the targets which lets us add functions by point and click (including a preview), but that is probably a discussion we should move to a new issue :-)

Let's make graphite a first class citizen in Team Dashboard :-)

**Comment by luxflux** [comment]
On 08/20/2012 10:28 PM, Frederik Dietz wrote:

> Thanks for the feedback. I've added double click handling, BTW ;-)

Cool! Thank you.

> On the other hand besides adding functions (and events) there's not
> much else I need. How about you? Do you need some/all the
> "configuration properties" offered by graphite and used in the
> dashboard? It would be cool to come up with a list of the most
> important ones and focus on these next (with or without the gem).

It would be nice to use all the functions, but its not easy to get
them all. And there are more of them every release...
The ones I need the most are:
scaleToSeconds
sumSeries
averageSeries
derivative
nonNegativeDerivative
scale

And I often use them in a cascade:
scale(sumSeries(path.to.*.value),"0.1")

For me it would be already sufficient if I could select the target in
the new "target-selection"-list and this selecting would fill another
(big) input-field (not textarea) which I could modify now with the
functions I need. Just by writing/editing the field. This way there is
no need for predefining the available functions and to have a fancy
algorithm to chain and to verify the input.

> Let's make graphite a first class citizen in Team Dashboard :-)

Totally agree on this!

**Comment by fdietz** [comment]
Hi again!

using a textfield definitely makes sense, but is very error prone. You can
very easily forget a closing parenthesis or have a typo in your
target/function.

I can imagine to at least offer an "almost" up to date list of available
functions. This could be used to simplify entering the functions in the
textfield or validating textfields and thereby preventing typos.

And/or additionally a live graph preview could help a lot and wouldn't be
that difficult since its all reusable Backbone views anyways.

The current target selection is as is complete and makes sense but
I'll have to work on an user interaction which includes all these new
aspects for the new release (planning to release v0.3 this week).

BTW, I've finally managed to include full Ganglia support including the
same target browsing support.

-Frederik

**Comment by luxflux** [comment]
Hi

On 08/23/2012 06:08 PM, Frederik Dietz wrote:

> using a textfield definitely makes sense, but is very error prone.
> You can very easily forget a closing parenthesis or have a typo in
> your target/function.

Hm, yeah. Maybe there is a possibility to list all the functions from
graphite? I googled a few minutes but didn't find something...

> And/or additionally a live graph preview could help a lot and
> wouldn't be that difficult since its all reusable Backbone views
> anyways.

This sounds good anyway! I'd even say that you could leave away the
function collection if you have a live preview, as you can directly
see whats happening.

> BTW, I've finally managed to include full Ganglia support including
> the same target browsing support.

Cool!

Regards
 raf
