### ISSUE TITLE
Graphite, Faraday and URL encoding

### ISSUE THREAD

**Issue by luxflux** [fdietz/team_dashboard#4]
The use of `farday` breaks the ability to use multiple targets from graphite. The problem is, that faraday encodes many targets as something like `target%5B%5D=host1.value&target%5B%5D=host2.value` which equals `target[]=host1.value&target[]=host2.value`. This is a PHP/Rails standard and django (on which graphite is based) does not like this. It just renders an empty array. The django way is to use something like `target=host1.value&target=host2.value`.

Faraday has an open [bug](https://github.com/technoweenie/faraday/issues/78) about this and also a (pull request)[https://github.com/technoweenie/faraday/pull/186] which would fix this.

What should can we do here? One solution would be to use the fork of @sqrrrl to get the support now. We could switch to another library, but I really dislike this option as faraday beats all the others in modularity.

**Comment by luxflux** [comment]
I created a bug report and a pull request to fix this in graphite (https://github.com/graphite-project/graphite-web/issues/42). But I don't think they will release today a new version just because of this :) So we still need a solution.

**Comment by fdietz** [comment]
Hi Raffael,

you are already quite busy on Sunday ;-) 

I've checked real quick and found another "issue" with faraday. All the existing code assumes that the URL is build in GraphiteUrlBuilder/GangliaUrlBuilder and requested as is (since net/http doesn't encode url params automatically). You can see in GraphiteUrlBuilder that I explicitly don't use the Rails conventions of the array[] params.

I found bugs in the encoding of the from/until date fields too ;-)

Example URL generated:
http://localhost/render?target=a&target=b&target=c&format=json&from=11:12_19700102&until=11:17_19700102

URL send by faraday:
http://localhost/render?target%5B%5D=a&target%5B%5D=b&target%5B%5D=c&format=json&from=11%3A12_19700102&until=11%3A17_19700102

So, the easiest "quick fix" would be to disable url encoding in faraday. I have to investigate if this is possible. In the future we would otherwise have to refactor the URL building anyways to handle url params specifically and let faraday do the encoding (including waiting for the pull request).

Cheers,
-Frederik

**Comment by fdietz** [comment]
BTW, I've just fixed the from/until escaping. So, at least all the code now correctly and more importantly consistently url encodes params.

**Comment by fdietz** [comment]
Just wanted to add that I refactored the code to make use of faradays encoding instead of doing it manually. Makes the url builder code simpler.

Still the problem persists with the array params

**Comment by fdietz** [comment]
There's another issue dealing with the array params https://github.com/technoweenie/faraday/issues/182. 

But, still waiting for a solution here :-(

**Comment by luxflux** [comment]
The pull request has been merged. Will be in next stable graphite-web release.

**Comment by fdietz** [comment]
Awesome! Thanks for looking into this!

**Comment by sporkmonger** [comment]
I think pull request technoweenie/faraday#199 probably solved this in a more permanent way.
