### ISSUE TITLE
Graphs For Today

### ISSUE THREAD

**Issue by martintsch** [fdietz/team_dashboard#43]
It would be nice to have the option in the Dashboard to show all the graphs only from today. Not last 3 hours but really starting at 00:00. Or even a custom Point in Time.

Will try to send a pull request...

Thanks ;-)

**Comment by fdietz** [comment]
It would be easy to add a Today, "This Week", etc. to the existing code without much change. 

Selecting a specific date range as in "a specific point in time" would be more involved since I'd have to make the widget editor more complex.

If added a first implementation for "Today" to get us started here!
