### ISSUE TITLE
My graphs are not smooth? But look ok in graphite 

### ISSUE THREAD

**Issue by cerw** [fdietz/team_dashboard#51]
Hi

1st of all, love this project ! great idea. 

2nd i am trying to play with few widges, and my load avarage looks very bad ? 
http://bb.macdaddy.com.au:3000/dashboards/1

Any idea why ?

thanks
Petr

**Comment by tubit** [comment]
Hi Petr,

what's wrong with your load average graph? 

cheers,
Dennis

**Comment by cerw** [comment]
Looks like when i set it min 3days it looks OK but if i have it for 3h the graphcs gets all funny..

**Comment by fdietz** [comment]
Hi Petr,

you could debug this further by looking into the rails log. There's an entry with the complete request to graphite. Paste that in your browser to check the json respose. It is quite easy to parse, since it contains an array of datapoints.

It would be interesting to know if you spot something funny when comparing the results of the different time ranges you selected!

Cheers,
-Frederik

**Comment by cerw** [comment]
Hi Frederik, 

Here is what is looks like http://d.pr/i/Mo3P, for some reason it does not display 3h, i think that's because of timezone issues (perth VS sydney). In rails logs files, i dont see anything unusual. 

But I think the grahps shoudl be more smooth? It looks like there are spaces between the values? 

p

**Comment by fdietz** [comment]
Hi Petr!

Looks like you have lots of gaps in your data. The graph rendering js library doesn't render anything if there are no datapoints available for a specific x-axis value. 

Since I haven't encountered this bug for myself, I can only guess. It could be a combination of the rendering js library granularity and your graphite configuration for the 12 hour bucket. Of course, that shouldn't happen and is probably a bug of either the js library or my usage of it!

As a quick fix you could use the "summarize" graphite function. 

Sorry, that I can't really give you any good advice here. On the positive side, I'm going to switch back to rickshaw.js since they now started supporting crucial features (like missing datapoints handling). So, this problem might be gone with the switch again!

I will post you an update when I got it running again!
Cheers, -Frederik

**Comment by fdietz** [comment]
Since we have several issues with the graphite json api not supporting all use cases and mismatches in other graphing libraries we used, we changed strategy to directly embed the new SVG graph returned by more recent graphite-web versions. This should solve all remaining issues. 

See Issue #80 for more information.

I therefore close this issue.
